# Generated by Django 3.1.6 on 2021-02-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('yearsExp', models.IntegerField()),
                ('baseSalary', models.IntegerField()),
                ('bonuses', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
            ],
        ),
    ]
