# Generated by Django 3.1.6 on 2021-02-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockroach_example', '0004_auto_20210207_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='baseSalary_currency',
        ),
        migrations.AlterField(
            model_name='user',
            name='baseSalary',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='bonuses',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
